def a():
    print(1, end="")
def b():
    print(2, end="")
def c():
    print(3, end="")
def d():
    print(4, end="")
def e():
    print(5, end="")
def f():
    print(6, end="")
def g():
    print(7, end="")
def h():
    print(8, end="")
def i():
    print(9, end="")
def j():
    print(0, end="")
h(),h(),j(),j(),e(),e(),e(),c(),e(),c(),e()